apiVersion: v1
kind: Secret
metadata:
  name: kenba-root-pass
type: Opaque
data:
  password: ZGVyZWs=
---
apiVersion: v1
kind: Secret
metadata:
  name: kenba-user-pass
type: Opaque
data:
  username: ZGVyZWs=
  password: bW90b3JvbGFtYjUyNQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: kenba-db-url
type: Opaque
data:
  database: a2VuYmE=
  url: amRiYzpteXNxbDovL2tlbmJhLW15c3FsOjMzMDYva2VuYmE=